### ISSUE TITLE
ostree: support installing a different kernel, e.g. a real time kernel

### ISSUE THREAD

**Issue by gicmo** [osbuild/osbuild-composer#1055]
`rpm-ostree`, used internally by ostree, will refuse to work when multiple kernels are installed on the target system:
```
error: Finalizing rootfs: During kernel processing: Multiple subdirectories found in: usr/lib/modules
```
This means, that we need to special case installing additional kernels, and can only allow to have one installed.

**Comment by gicmo** [comment]
cc @mrguitar @jarcher

**Comment by gicmo** [comment]
For the record: copr repo with real time kernel for testing purposes: https://copr.fedorainfracloud.org/coprs/ycollet/linuxmao/

**Comment by achilleas-k** [comment]
Discussed the issue with both of you in person; summarising here for posterity and to clarify.

Since the origin of this feature request is specifically about the RT kernel, we can add an a field to the `OSTreeImageOptions` to specify the desired kernel in ostree images.  Implementations of the `Packages()` method of the `ImageType` interface should remove all other kernels from the package list when appropriate.

This is a very specific solution and wont solve the general case (custom repos, other kernels, etc), but it _fixes_ the ostree builds with the RT kernel.

**Comment by ondrejbudai** [comment]
@achilleas-k isn't this solved? https://github.com/osbuild/osbuild-composer/blob/main/docs/news/28/kernel-customizations-name.md

**Comment by achilleas-k** [comment]
Yup.  Closing.
