### ISSUE TITLE
use different container registry than docker.io

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#1064]
The koji test uses `docker.io/library/postgres:12-alpine`. Sadly, `docker.io` recently introduced rate-limiting that failed some of our builds. Therefore, we have to say goodbye to `docker.io` and get the images from somewhere else.

**Comment by teg** [comment]
Should we just move to `quay.io`? @gicmo @dvdhrm, thoughts?

**Comment by ondrejbudai** [comment]
That was my thought as well. Would be awesome to eat our own dog food. Other suggestions are also welcomed!

**Comment by dvdhrm** [comment]
We had several outages of `quay.io` in the past, which is why I mirrored everything on `docker.io`. But you can freely switch back to `quay.io` for now, the current infrastructure still mirrors to both. The primary target always was `docker.pkg.github.com`, but this registry was deprecated few weeks ago by GitHub, and is meant to be replaced by `ghcr.io` (Git Hub Container Registry).

I hope to use GHCR in the future for everything, but it is still in Beta :(

**Comment by ondrejbudai** [comment]
Fixed by #1066
