### ISSUE TITLE
panic in koji-finalize job

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#1101]
```
osbuild-worker[17136]: Running 'koji-init' job 8f33490e-4175-488a-a22e-772a1f2b3233
osbuild-worker[17136]: 2020/11/24 10:49:10 Job 8f33490e-4175-488a-a22e-772a1f2b3233 finished
osbuild-worker[17136]: Waiting for a new job...
osbuild-worker[17136]: Running 'osbuild-koji' job abe229da-aec7-4905-9de7-d616adf4973a
osbuild-worker[17136]: 2020/11/24 10:49:10 Job abe229da-aec7-4905-9de7-d616adf4973a finished
osbuild-worker[17136]: Waiting for a new job...
osbuild-worker[17136]: Running 'osbuild-koji' job 1b365b23-4564-451a-a157-0626819aa338
osbuild-worker[17136]: 2020/11/24 10:49:10 Job 1b365b23-4564-451a-a157-0626819aa338 finished
osbuild-worker[17136]: Waiting for a new job...
osbuild-worker[17136]: Running 'koji-finalize' job 68f9b26a-61f3-4e4f-aec3-978fba806465
osbuild-worker[17136]: panic: runtime error: invalid memory address or nil pointer dereference
osbuild-worker[17136]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x56107a02b2b5]
osbuild-worker[17136]: goroutine 1 [running]:
osbuild-worker[17136]: panic(0x56107a1b68e0, 0x56107a51eda0)
osbuild-worker[17136]:         /usr/lib/golang/src/runtime/panic.go:1064 +0x545 fp=0xc0000db7c0 sp=0xc0000db6f8 pc=0x561079aeb2a5
osbuild-worker[17136]: runtime.panicmem(...)
osbuild-worker[17136]:         /usr/lib/golang/src/runtime/panic.go:212
osbuild-worker[17136]: runtime.sigpanic()
osbuild-worker[17136]:         /usr/lib/golang/src/runtime/signal_unix.go:742 +0x413 fp=0xc0000db7f0 sp=0xc0000db7c0 pc=0x561079b011b3
osbuild-worker[17136]: main.(*KojiFinalizeJobImpl).Run(0xc000010648, 0x56107a28ee60, 0xc000596980, 0xc00005d900, 0x56107a28ee60)
osbuild-worker[17136]:         /home/obudai/work/osbuild-composer/rpmbuild/BUILD/osbuild-composer-eac14367c436b2b55b2326ae537fc5859fb26390/_build/src/github.com/osbuild/osbuild-composer/cmd/osbuild-worker/jobimpl-koji-finalize.go:130 +0x335 fp=0xc0000dbaf8 sp=0xc0000db7f0 pc=0x56107a02b2b5
osbuild-worker[17136]: main.main()
osbuild-worker[17136]:         /home/obudai/work/osbuild-composer/rpmbuild/BUILD/osbuild-composer-eac14367c436b2b55b2326ae537fc5859fb26390/_build/src/github.com/osbuild/osbuild-composer/cmd/osbuild-worker/main.go:192 +0xbc4 fp=0xc0000dbf88 sp=0xc0000dbaf8 pc=0x56107a0311e4
osbuild-worker[17136]: runtime.main()
osbuild-worker[17136]:         /usr/lib/golang/src/runtime/proc.go:204 +0x209 fp=0xc0000dbfe0 sp=0xc0000dbf88 pc=0x561079aedec9
osbuild-worker[17136]: runtime.goexit()
osbuild-worker[17136]:         /usr/lib/golang/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0000dbfe8 sp=0xc0000dbfe0 pc=0x561079b20601
```

I investigated what happened:

1) `koji-init` failed. The reason doesn't matter much, this can happen in the production (e.g. network issues)

2) `osbuild-koji` updated the job but didn't set the `result.OSBuildOutput`, see https://github.com/osbuild/osbuild-composer/blob/bbaffa33c904dee2f76620f1db20d5bbb238b122/cmd/osbuild-worker/jobimpl-osbuild-koji.go#L87

3) `koji-finalize` crashed because it accessed `result.OSBuildOutput`, see https://github.com/osbuild/osbuild-composer/blob/bbaffa33c904dee2f76620f1db20d5bbb238b122/cmd/osbuild-worker/jobimpl-koji-finalize.go#L130

My thoughts:

- `osbuild-koji` should always set `result.OSBuildOutput`, or not update the job (in case of a worker error)
- this is not a worker error, so `result.OSbuildOutput` should be set
- we need to run `osbuild` in `osbuild-koji` even though `koji-init` failed
- this is stupid, we're wasting resources

The big question:

Should failed jobs run its dependants? In this case, jobqueue would need to know if a job failed. It currently doesn't know that.

Tagging @larskarlitski and @teg for more thoughts.

**Comment by ondrejbudai** [comment]
We can set `result.OSBuildOutput.Success` to `false` in `osbuild-koji` if `koji-init` failed...

**Comment by teg** [comment]
Ah, this really is not ideally explained (nor implemented), but @larskarlitski and I discussed this as some length. The ideas were:
 - the job queue should be stupid and not have any conditionals, all queued jobs are always run, even if they end up being noops. The reason for this is that we do not want the job queue to contain some sort of DSL or advanced logic, but rather have each job type implementation do the necessary logic.
 - even if a job fails, one of its dependencies may still need to be executed, possibly just to clean up. If `koji-init` succeeds, but `osbuild-koji` fails, then `koji-finalize` must still refund the `build_id` and bark the build as `failed`.
 - we should not duplicate information in the different job results, so if `koji-init` failed, `koji-finalize` should read that from the `KojiInitJobResult` directly, rather than indirectly via `OSBuildKojiJobResult`.

The current implementation leaves much to be desired as some helpers to deal with all of this would have made it much clearer, I believe.

> - `osbuild-koji` should always set `result.OSBuildOutput`, or not update the job (in case of a worker error)
> - this is not a worker error, so `result.OSbuildOutput` should be set
> - we need to run `osbuild` in `osbuild-koji` even though `koji-init` failed
> - this is stupid, we're wasting resources

I think we should just set `result.OSbuildOutput` if `osbuild` was actually run, and I think we should not run `osbuild` if we know it is pointless. I think the fix for this bug is for `koji-finalize` to not try to access `result.OSBuildOutput` as it should know that `koji-init` failed. We should introduce some helpers to make this sort of logic more obvious. I think.
