### ISSUE TITLE
Tests that use podman fail on F32

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#1135]
From `/usr/libexec/tests/osbuild-composer/koji.sh`:

```
Error: default OCI runtime "crun" not found: invalid argument
```

It happened for example here: https://osbuildci.cloud.paas.psi.redhat.com/blue/organizations/jenkins/osbuild%2Fosbuild-composer/detail/PR-1131/5/pipeline/179

**Comment by atodorov** [comment]
@ondrejbudai few notes here:

1) I've found https://github.com/containers/podman/issues/8227 and it looks like the problem is an older version of podman. That issue says 2.1.1 fixes the problem

2) From what I can see we're using v3.0.1 and what's more containerbuild (which uses podman) is executed on Fedora 33 now.

3) From what I can see we haven't had this issue for a while

I think we can close this issue as not being relevant, what do you think ?

**Comment by ondrejbudai** [comment]
Yeah, this should be fixed now.
