### ISSUE TITLE
CI: confusing failure - wrong version built?

### ISSUE THREAD

**Issue by achilleas-k** [osbuild/osbuild-composer#1527]
I probably didn't investigate this enough but I wanted to note it down to have a better look tomorrow.

There's something odd about the current CI failure in main ([CI pipeline for 6e22e1de64c18299c80e13a7b9a60049b16ea040](https://gitlab.com/osbuild/ci/osbuild-composer/-/pipelines/331383627)).

The API test with argument `aws.s3` failed with the message: 
```
+ echo 'Unknown cloud provider '\''aws.s3'\''. Supported are '\''aws'\'', '\''gcp'\'''
Unknown cloud provider 'aws.s3'. Supported are 'aws', 'gcp'
```
[Link to job](https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1397504979#L2423)

The `api.sh` script for commit 6e22e1de64c18299c80e13a7b9a60049b16ea040 is clearly the correct (up-to-date) one https://github.com/osbuild/osbuild-composer/blob/6e22e1de64c18299c80e13a7b9a60049b16ea040/test/cases/api.sh#L65

Is CI for main using older versions of the osbuild-composer-tests RPM?

**Comment by atodorov** [comment]
https://gitlab.com/osbuild/ci/osbuild-composer/-/pipelines/331383627 includes the `Prepare-rhel-internal` job which downloads osbuild-composer-tests from the latest nightly tree, which is always older than main. 

The failure is probably expected b/c the nightly RPM doesn't always include all of the test scripts. 

The reason status on main was updated is because both pipelines use the same commit number and the update_github_status.sh script simply overwrites the previous value.

**Comment by achilleas-k** [comment]
Thanks for the explanation.  That clears it up.
