### ISSUE TITLE
Fedora 34 - Produces refs to fedora/33

### ISSUE THREAD

**Issue by bstin** [osbuild/osbuild-composer#1802]
**Describe the bug**
When building an iot-commit.tar from Fedora 34, the resulting tar file points to refs/heads/fedora/33/x86_64/iot

**Environment**
 * OS version (`/etc/os-release` and `/etc/redhat-release`):
 ```
# cat /etc/os-release
NAME=Fedora
VERSION="34 (Server Edition)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora 34 (Server Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f34/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=34
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=34
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Server Edition"
VARIANT_ID=server

# cat /etc/fedora-release 
Fedora release 34 (Thirty Four)
```
 * osbuild-composer version (`rpm -qi osbuild-composer)`
```
Name        : osbuild-composer
Version     : 31
Release     : 1.fc34
Architecture: x86_64
```

**To Reproduce**
 * Generate a Commit.tar file 

**Expected behavior**
Should produce refs that point to fedora/34 (or whatever current version)

**Additional context**
Not sure if this is related, but this server was originally a Fedora33 server which I upgraded to Fedora34. Not sure if that is related in someway?

**Comment by thozza** [comment]
Hello.

Thanks for reporting this issue.

While we decided to use aliases for F34 image definition to F33 definition, we missed to rework the `imageType`'s `OSTreeRef()` to not return the `ostreeRef` value defined in the package, but rather the value from the distribution structure. From what I checked, the code in all APIs always calls the `OSTreeRef()` only on an `ImageType` structure, never on the `Distribution`.

The problematic code is:
 
https://github.com/osbuild/osbuild-composer/blob/b42cfc2e700880614255f423461c97d65c515027/internal/distro/fedora33/distro.go#L178-L183

The fix would be probably to return the `ostreeRef` value defined in the image's distribution, when calling the `OSTreeRef()` on `ImageType`. Something like:
```golang
func (t *imageType) OSTreeRef() string {
	if t.rpmOstree {
		return t.Arch().Distro().OSTreeRef()
	}
	return ""
}
```

The same problematic code exists in RHEL image definitions as well, but does not create any issues, because we currently don't alias RHEL image definitions between major releases, only minor releases. So the situation is a bit specific to Fedora's release cycle.

The RHEL image definition code example:
https://github.com/osbuild/osbuild-composer/blob/b42cfc2e700880614255f423461c97d65c515027/internal/distro/rhel85/distro.go#L210-L215
