### ISSUE TITLE
iot-installer defaults to btrfs in Fedora 38

### ISSUE THREAD

**Issue by paulwhalen** [osbuild/osbuild-composer#3310]
**Describe the bug**
A new installation of Fedora 38 IoT using an iso created with osbuild defaults to btrfs, rather than ext4/lvm. 

**Environment**
 * Fedora 38
 * koji

**To Reproduce**
 *Create iso using iot-installer type

**Expected behavior**
Defaults to ext4/lvm

**Comment by 7flying** [comment]
@supakeen I was working on this since we also want to align the IoT simplified-installer to what RHEL9 has (LVM + luks, but this one with ext4 instead of xfs)

Do you want to hand over this issue to me? I was trying to tackle everything at once, plus some changes that might be needed in coreos-installer-dracut.

**Comment by supakeen** [comment]
@7flying If you want to take it you can take it. However, this issue seems to mention iot-installer which is Anaconda, and not the CoreOS Simplified Installer (which is the iot-simplified-installer type, which hasn't been merged yet).

**Comment by 7flying** [comment]
> @7flying If you want to take it you can take it. However, this issue seems to mention iot-installer which is Anaconda, and not the CoreOS Simplified Installer (which is the iot-simplified-installer type, which hasn't been merged yet).

Yes, my bad :woman_facepalming: . We'll be handling both, first the simplified-installer, and then this one with the iot-installer.
