### ISSUE TITLE
tests/image: Test ami images on AWS

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#337]
Currently, we are only booting the ami images locally using qemu. We should switch the ami test to do a proper test in the real AWS environment. Currently, there's a minor issue with it: The image tests use `osbuild` instead of `osbuild-composer` to do the image build, because it's currently impossible to disable updates repository in composer and we don't want the tested images to change all the time. Therefore, we don't have a simple way to upload the image to AWS. For now, let's just directly use the code from `internal/upload` to do the upload and we can switch to `osbuild-composer` later.

What is needed:
- create a new boot type in image tests
- use the functions in `internal/upload` to do the upload
- create and run a VM from the uploaded image in AWS
- try to connect to it using ssh and get the machine's status from `systemctl --wait is-system-running`
- tear everything down

Also, a workaround/fix for #257 is needed.

**Comment by atodorov** [comment]
This is the same as #316 but provides more step-by-step details. 

@ondrejbudai can you explain what exactly the problem with the updates repo is ?  Why would it be a problem for the image tests that the resulting image is changing ? Can't we (during testing) just remove the updates repository ?

**Comment by teg** [comment]
@atodorov in general, we want to make sure that our tests are not dependent on external changes (to the degree possible). So we should test against a fixed known-working repository for a given output type, so that if fedora contains a broken package that does not fail our tests (they should of course not, but that's out of our hands). Ideally, fedora gating tests would build images before pushing packages to updates, but I think that's a separate discussion and should be done on their end, not as part of our CI.
Using the standard `weldr` API, we cannot remove any of the official repositories. We could change the files in the filesystem for our tests, but if we want to go the path of specifying the repositories, I think it makes sense to use the RCM API as that allows exactly that (long-term, we hope to build the `weldr` API on top of the RCM API to minimize the duplicate code-paths, so in that case it makes the most sense to do these low-level tests in terms of the lowest-level API).

**Comment by ondrejbudai** [comment]
Tom wrote that nicely, thanks!

@atodorov sorry, I'm stupid, I totally forgot the issue you opened. Thanks for "reusing" it for Azure tests! :slightly_smiling_face:

**Comment by atodorov** [comment]
> @atodorov in general, we want to make sure that our tests are not dependent on external changes (to the degree possible). So we should test against a fixed known-working repository for a given output type, so that if fedora contains a broken package that does not fail our tests (they should of course not, but that's out of our hands). 

I agree that we should not be dependent on external factors as much as possible. However in the past it is not packages, but repodata mismatch on mirrors that was breaking RPM downloads. I was thinking that the reason for not using updates repo is b/c NVR will be different from what we have in json files and comparing the resulting images will start failing. 

If the reason we don't want to use update repos is because we don't want to be dependent on possible failures due to broken RPMs this IMO is not a big concern. I don't see a reason why not to use the updates repository and actually use osbuild-composer. 

However all of that is independent of the work required to build & boot an AMI in AWS. I will open another issue with this comment to discuss this.
