### ISSUE TITLE
Split the job queue from the store

### ISSUE THREAD

**Issue by larskarlitski** [osbuild/osbuild-composer#342]
The store contains two main things:

1. User state: blueprints (and their history), additional sources
2. The compose queue: past, running, and pending composes

We have two APIs for **osbuild-composer**: `weldr` and `rcm`. `weldr` needs both (1) and (2), but `rcm` only needs (2).

Going forward, we'd like to put the queue into a proper database, so that it can scale to many image builds. I don't think there's a need to put (1) into a database just yet, because of the nature of the `weldr` API (local socket only, not meant for 1000s of blueprints). And even if we did, it would probably have different access policies than the one for the queue.

Thus, I propose splitting (1) and (2). Specifically, I'd like to move the queue into the `jobqueue` package, which already contains the worker-facing part of the queue. It would be an interface with different backends: as a first step, a JSON-file backend, similar to the store (`/var/lib/osbuild-composer/queue.json`) gives us the same functionality that we have right now. Going forward, we could add one that is backed by a database (out of scope for this issue).

A side benefit would be a much simplified `store` package. It has a few too many moving parts for my taste right now­—especially considering the amount of locking and goroutines in there.

@msehnout, @dvdhrm, @teg curious to hear your thoughts about this.

**Comment by teg** [comment]
This makes perfect sense to me! Thanks for writing it up!

**Comment by ondrejbudai** [comment]
I have a thought or two too! :raising_hand_man: 

### Unit testing
Since the beginning of times we have `stateDir *string`. When store is used in the production code, it's set to `STATE_DIRECTORY`. However, in the unit tests it's set to `nil`. Unfortunately, this means that we need to check for nil-ness in several places and this just feels weird. To make things worse, in several places the checks are missing and the behavior is therefore non-consistent (I'm guilty of this offense).

I feel like this weirdness should be removed. I can think of two solutions:

1) Make a very thin wrapper responsible for reading/writing data from/to filesystem. Then, make a mock which does all of this in-memory.

2) Make `stateDir` non-pointer and set up temporary directory in the unit tests. This solution may be a bit easier, however I'm not sure if I like the idea of unit tests writing data to disk.

It may be out of scope of this issue, however I feel like these things are closely connected.

### Store versioning

We discussed that yesterday. We want to start maintaining backwards compatibility soon, so we need to version the store to be able to do migrations (that's the word!) from an older version to a newer one.

I think this is probably out of scope of this issue, but I wanted to mention it here if you have any thoughts and we can create a separate one later.

**Comment by larskarlitski** [comment]
> I feel like this weirdness should be removed. I can think of two solutions:

That is weird indeed! Thanks for brining it up.

> 1. Make a very thin wrapper responsible for reading/writing data from/to filesystem. Then, make a mock which does all of this in-memory.
>
> 2. Make `stateDir` non-pointer and set up temporary directory in the unit tests. This solution may be a bit easier, however I'm not sure if I like the idea of unit tests writing data to disk.

I think I prefer the first suggestion. Like I mentioned in the initial comment, I'm planning to have the first queue backend be a simple file (`queue.json`), which would need the same semantics as well and could benefit from such a wrapper. I'll include it in the patch for this work.

> # Store versioning

Yeah, I think this is out of scope for this issue. I don't have any new thoughts, but let make an issue (done: https://github.com/osbuild/osbuild-composer/issues/349)

**Comment by larskarlitski** [comment]
https://github.com/osbuild/osbuild-composer/pull/487 is another move towards this.

@obudai unfortunately it cannot get rid of `stateDir`, because that also includes the `outputs` directory. I have added a few tests in that PR which write files to temporary directories. I think it's ok to do this from unit tests, I think. Why are you concerned about that?

**Comment by ondrejbudai** [comment]
I think I had just performance concerns, but I changed my mind, this is a much cleaner solution imho. However, I still think we should remove the pointer from the `stateDir` parameter of `store.New` method and force the tests to always pass a directory. This way we can remove all the `stateDir == nil` code paths in the store.
