### ISSUE TITLE
tests/image: Use empty blueprints to build images

### ISSUE THREAD

**Issue by atodorov** [osbuild/osbuild-composer#351]
ATM `osbuild-image-tests` uses the JSON files under `test/cases/` to build an image, verify the resulting image contents match what is described in the JSON file and also specify how to boot that image (qemu, nspawn).  

These JSON files appear to be osbuild pipeline specifications.

I can see there is also a `blueprint` section in the JSON file, not sure how that relates to the regular TOML blueprint. Sometimes this section is empty.

I also see we're adding the openssh-server package when building these images (not always). I suspect this is a requirement so we can ssh into the booted image afterwards but goes against the idea to use empty blueprints. I'm not sure if there is another way around this or if this is a problem at all.

Note: could be related to #350 and the fact that this test is still not using `osbuild-composer`.

@teg, @ondrejbudai can you explain a bit more how this works and what needs to be changed here in your opinion?

**Comment by teg** [comment]
@jkozol is just finishing work on cleaning this all up. I think it would be nice to document the current intentions in a `README.md` file in the test case directory.

Firstly, `weldr` supports blueprints in both JSON and TOML, we are using JSON everywhere in these tests, but there should be a one-to-one correpsondence (and that TOML also works is tested as part of the API tests).

Each of the test cases specify:
 - A compose request. This is a combination of distro/architecture/image type/blueprint and a few other pieces of information.
 - An osbuild manifest. This is the input to the low-level osbuild tool that fully specifies how to build the image. Our tests verify that this manifest is the output from the given compose request.
 - Image info output. Our tests build the image form the given manifest and verifies that the image info matches what is given here.
 - A boot section. This specifies how the image should be boot tested. For now we test in qemu or nspawn, depending on the image type, but in the future we will also support booting in the various cloud providers. Our tests boot the produced image and verifies that we can connect to it over ssh and that systemctl reports that the system has booted.

Currently all the blueprints are chosen to be the minimal blueprints needed in order to pass the boot tests. You'll see that the AMI images use empty blueprints as cloud-init means we don't need to insert any configuration, most other image types need the ssh keys to be inserted into the image, and some image types even need the ssh server to be installed.

In the future we could extend the tests by adding additional blueprints to verify additional properties, but for the time being we are trying to flesh out the boot tests to cover more architectures and more methods of booting.

**Comment by atodorov** [comment]
From chat logs:

> I think my beef is with the fact that these tests do not call osbuild-composer directly but osbuild instead. Which is in fact #350. Thinking about it I think 351 can be closed

>> @tomegun does a composer-cli compose start translate into the compose-request JSON section ?
>
> Yes, with the difference that composer cli builds an image from the official repos, but in the JSON sections we specify the repos. That allows us in the image tests to test against a fixed and known working repo snapshot.


IMO this can safely be closed.
