### ISSUE TITLE
When AMI image is created in cockpit-composer, it's shown as Alibaba

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#369]
When I create an AMI image in composer-composer, it's shown as:

> **test-0.0.2-Alibaba**
> Type **Alibaba**

This does not affect the actual image - the correct `.tar.xz` for aws is created. I think this is most probably connected to @msehnout's refactoring of types.

**Comment by msehnout** [comment]
Yeah, it's possible. I should really prioritize the rewrite of remaining parts.

**Comment by msehnout** [comment]
It's this function:
https://github.com/osbuild/osbuild-composer/blob/afa4975a15618f775849ce0415201ab76af691d7/internal/common/types.go#L227

It works like that because Alibaba and Google Cloud use the `ami` type as well. So we can either come up with a name for them and use it in the Weldr API or create a quick workaround (like in case of ami, just return aws)...

But if we want to extend the API with Alibaba and Google Cloud support without renaming the rest I suggest to just use something like: `alibaba` and `google-cloud` as the "compat" string.

**Comment by msehnout** [comment]
I'm postponing my work on this until #375 lands.

**Comment by teg** [comment]
Makes sense to postpone, let's see how it all shakes out after some more cleanups land.

**Comment by jgiardino** [comment]
In case it helps, here's what I'm seeing today. 
Alibaba no longer displays 😄👍 , but now google cloud displays 😞👎 :

![image](https://user-images.githubusercontent.com/21063328/78297936-acedc400-74fe-11ea-8fc2-c3c4e34dae7f.png)
