### ISSUE TITLE
Error handling in blueprint.go

### ISSUE THREAD

**Issue by jrusz** [osbuild/osbuild-composer#386]
The returns in this function here: 
https://github.com/osbuild/osbuild-composer/blob/master/internal/blueprint/blueprint.go#L43 
are never called since you can't pass it a wrong `Blueprint` type. It's not possible to cover it with unit tests the way it's written now. 

I want to propose a change where those returns will be remove and `err` will be returned on the last line where it can be handled by the unit test. 

The `err` is used there twice and my first attempt is probably not the right solution to this so I'm looking forward to some comments. I can think of returning `err1` and `err2` but that might be something we don't want.

**Comment by atodorov** [comment]
> The returns in this function here:
https://github.com/osbuild/osbuild-composer/blob/master/internal/blueprint/blueprint.go#L43
are never called since you can't pass it a wrong Blueprint type. It's not possible to cover it with unit tests the way it's written now.

In the case that passing invalid values isn't possible then you are looking at mocking. That is changing behavior of external dependencies. In this case `json.Marshall` is external to `DeepCopy`, which is the subject under test.

Mocking `json.Marshall` to always return an error will cause the traversal of lines 45 + 46. Then you can assert on the returned values.

For some high-level reference on the subject see,
http://atodorov.org/blog/2019/04/05/the-art-of-unit-testing/, section
*What is the difference between a double, stub, mock, fake and spy?*

In this particular context it doesn't make a lot of sense to try hard to cover these couple of lines b/c we're not getting enough information to warrant ROI. However I still think it is a valuable exercise b/c the testing scenario is very simple and will allow for very clean understanding how to mock things in Go.

A quick search revealed these 2 articles but I don't know how accurate or usable they are to you:
https://blog.learngoprogramming.com/how-to-mock-in-your-go-golang-tests-b9eee7d7c266
https://deployeveryday.com/2019/10/08/golang-auth-mock.html

**Comment by jrusz** [comment]
@atodorov this sounds promising, will look trough this, thanks!

**Comment by teg** [comment]
I think, in general, when we have code paths that cannot be reached, and we are confident cannot be reached, the correct solution is to add a
```
if err != nil {
    panic()
}
```
That documents the intentions, and gives us a stack-trace in case our assumption were wrong. In this particular case, the only way for the marshaller to fail is if the passed type cannot be marshalled, which would then mean that the the panic would either always or never be triggered. So if we were to make a mistake and make `Blueprint` unmarshallable, then we would trigger the panic on every unit-test run.

More generally, the only reason this codepath exists at all, is the lack of expressivity in the Go typesystem, which sort of makes me feel ok about using panics to assert things that should be caught at compile time.

cc: @larskarlitski, @ondrejbudai, @msehnout, @dvdhrm

**Comment by larskarlitski** [comment]
I agree with @teg's suggestion. I've opened a PR which puts this into the `docs` directory: https://github.com/osbuild/osbuild-composer/pull/391

**Comment by atodorov** [comment]
For a very clean example (minor changes requested) of how to mock things see #398 

Based on previous comments it doesn't look like there's anything else left to do here. Closing.
