### ISSUE TITLE
Unused code in internal/blueprint/customizations.go

### ISSUE THREAD

**Issue by jrusz** [osbuild/osbuild-composer#402]
I am currently working on a test for the file in $SUBJ and I believe I came across some lines that will never be run. Please take a look at this: https://github.com/osbuild/osbuild-composer/blob/master/internal/blueprint/customizations.go#L75
Those returns are nearly in all of the functions but I think they'll never be called because these are the methods for `Customizations struct` and when I call them the structures will never be just one `nil`. The fields in the structure will have `nil` values but the mentioned `if` will not be called it would have to be `if c.GetHostname == nil` to actually go through that. If I remove it and leave with just `return c.Hostname` it will return `nil` if it's called upon an empty `Customizations struct`. 

So my suggestion is to remove those returns. I'll add it to my next PR if you agree.

I hope it's clear what I mean, I can demonstrate with some examples if it's not.

**Comment by larskarlitski** [comment]
This seems to have been a refactoring mistake in 7957feff48c0a7f01205adf9615b1ae4a8678945. We were checking if the `Customizations` field on a blueprint was set.

I think it's fine to remove them. @teg?

**Comment by ondrejbudai** [comment]
We cannot remove them, because `blueprint.Customizations` can indeed be true. In Go, it's just fine to call a method with `nil` receiver. See:
- https://tour.golang.org/methods/12
- https://play.golang.org/p/5ZxL80qq6c9

The `c == nil` path is indeed used in the case when user doesn't want any customizations. Therefore, the tests should cover these paths.

Actually, we should refactor the customizations at some point. The code was moved around several times now and a deduplication would be nice. However, I think it isn't particularly easy to do it.

**Comment by larskarlitski** [comment]
Oh, I thought we checked in the distros whether it is set to `nil`, but we don't indeed. Thanks @ondrejbudai and sorry for the confusion.

**Comment by jrusz** [comment]
@ondrejbudai Right I just tested calling the methods on `Blueprint` which has no `Customizations` and it goes that way. Thanks, I'll add it to my PR :)
