### ISSUE TITLE
Define or remove ext4 image type

### ISSUE THREAD

**Issue by msehnout** [osbuild/osbuild-composer#494]
As discussed in PR #472 we are not sure what this image type should represent, so we should either write a definition ourselves or drop it.

**Comment by bcl** [comment]
Looking back in time :) livemedia-creator added --make-fsimage because it is the basis for the iso's root filesystem creation. You can make the iso in 2 steps, creating a fsimage first, and then feeding that into --make-iso instead of making a new one.

Outside of that I'm not sure where it is useful, Anaconda's liveinst supports tar which is probably a better choice if you are using that.

So I'm ok with removing this.

**Comment by teg** [comment]
This has been removed. Thanks!
