### ISSUE TITLE
Define Schutzbot testing matrix

### ISSUE THREAD

**Issue by major** [osbuild/osbuild-composer#517]
As of today, we're testing `osbuild-composer` in this way with Schutzbot Jenkins in 3 jobs:

1. fedora31
    * dnf-json
    * image *(WIP)*
    * osbuild-tests
    * rcm
    * weldr

2. fedora32
    * dnf-json
    * image *(WIP)*
    * osbuild-tests
    * rcm
    * weldr

3. rhel82
    * dnf-json
    * osbuild-tests
    * rcm
    * weldr

The image tests will take a long amount of time to complete since each one takes 3-5 minutes. The AWS boot tests could take 15-20 as we wait for AWS to fully import the image. :sob: 

It probably makes sense to cut the jobs in half so we run all non-image tests in one job and all the image tests in the other one. It may make sense to define a matrix like this:

* Distributions: Fedora 31, Fedora 32, RHEL 8.3 (nightly compose)
* Test jobs:
    1. dnf-json, osbuild-tests, rcm, weldr
    2. image (including AWS/Azure/GCP boot)

Does this make sense? @teg

**Comment by atodorov** [comment]
> image (including AWS/Azure/GCP boot)

FYI on the lorax-composer side of things each of these is a separate job.

IMO the separation makes sense. If it's not much overhead I would also prefer to have each of these tests in a separate job which will report its own status on the pull request and we'll immediately know which job failed instead of going through the logs.

**Comment by major** [comment]
The only real limitations we have here are:

1. Each test runs on a single VM at a time, so this creates additional expense
2. Each test appears as a GitHub check, so the list could get a bit long in the interface

**Comment by major** [comment]
Should our test matrix look something like:

1. dnf-json, osbuild-tests, rcm, weldr
2. image tests
3. AWS boot
4. Azure boot
5. GCP boot

🤔

**Comment by teg** [comment]
I think the basic matrix should be one run per distro / architecture combo. We could split it to further too, and then I think what you described makes sense. @ondrejbudai do you think we could reasonabley run the image tests in parallel, or at least run the uploading part in parallel? That way we might get away with not running each boot test in a different VM.

**Comment by major** [comment]
@teg So run three jobs, one per distro, with all of the tests in it? I thought we agreed that it would take much too long for that.

**Comment by teg** [comment]
No objections at all to splitting it up further, just wanted to point out that I think distro/arch are the most important, as those I see no way to optimize. The setup you describe makes sense.

**Comment by major** [comment]
Okay, I'll see if I can split the jobs into per-distro first, and then split it further beyond that.

**Comment by ondrejbudai** [comment]
I agree with @teg, one job for one distro sounds good. If we need to split the jobs to lower the running time, I'm completely fine with that. Let's talk about how we can speed up the builds:

## Running jobs in parallel

This is somewhat tricky currently because we cannot run more instances of osbuild in parallel because of some issues in the object store. I think @dvdhrm is currently doing some work in that field, so maybe he can look into it?

I tried a workaround ( https://github.com/ondrejbudai/osbuild-composer/commit/78ad614d6eb72d3f757c90e9dc39524dbe911c80 ), that allows the tests to run in parallel while preventing to run multiple osbuild instances by a mutex. This could really help with the AWS uploads that can take from 10 to 20 minutes.

## Caching the build pipeline

The build pipelines are the same for all the image types, therefore caching them would surely help. However, it's needed to pass the buildpipeline's tree ID to osbuild to enable the caching and getting the tree ID is currently not particularly easy. @gicmo can help us in this field.

## Caching the rpms

This sounds like it can help, but can it really? I think @major said that he gets very high download speeds with his awesome nearest mirror `sed`-powered selector, so this could have potentially a very little effect.
