### ISSUE TITLE
Handle very slow AWS image imports

### ISSUE THREAD

**Issue by major** [osbuild/osbuild-composer#554]
Some AWS regions, especially `us-east-1`, can take a very long time to import images. In the best cases, this usually takes 10-15 minutes. In some other cases, it can be an hour or longer.

The AWS modules in osbuild-composer wait a very long time for images already, but we may need some kind of retry mechanism when an image has failed to import or is taking a very long time.

The `us-east-1` region is very popular in the US because it was AWS' first region and many services that people want to consume are located there.

**Comment by teg** [comment]
I think we should do this by exposing the "registering" state (or whatever we want to call it), and allowing the user to cancel when they decide they've had enough (rather than us having some arbitrary timeout as we do now).

Or can we do something more clever? What did you have in mind with "retry mechanism"?

**Comment by larskarlitski** [comment]
https://github.com/osbuild/osbuild-composer/pull/633 turns off timeouts, which is a step towards that. @major is this what you had in mind with this issue, or something that's more complete?

**Comment by major** [comment]
We can probably close this now since this will tide us over for a while.
