### ISSUE TITLE
RFC: Do we want to support building images with unsigned rpms?

### ISSUE THREAD

**Issue by jrusz** [osbuild/osbuild-composer#614]
I recently discovered with @ondrejbudai that rhel nighty repos contain unsigned rpms and that the image build fails because of it. I discussed this briefly with @jikortus and we came to a conclusion that  some customers might make a use of a feature where they could disable this rpm signature checking, for example if they have their own mirror which contains some unsigned packages. It is a dnf feature as well so someone has to be using it. Maybe setting some environment variable to disable this checking would work? What do you think?

**Comment by teg** [comment]
I am not sure. Some considerations:
 - Currently we enable signature verification for all rpms, we could disable it for all, but if we want it configurable, maybe we want it per-rpm?
 - If the repo metadata is trusted, then there is no need to verify the rpms at all. The reason is that the metadata contains the contant hashes for all the rpms we install, and we verify that this matches. Should we rather consider disabling the verification unconditionally?

@larskarlitski @gicmo @dvdhrm we discussed things like this before. Thoughts?

**Comment by larskarlitski** [comment]
>     * Currently we enable signature verification for all rpms, we could disable it for all, but if we want it configurable, maybe we want it per-rpm?

How would osbuild-composer choose for which rpms to enable verification? I think having it per-repository would solve all the cases @jrusz describes, for example, using base repos of a distro (verified) + some custom repos (unverified).

 (Or do you mean in osbuild's file source?)

>     * If the repo metadata is trusted, then there is no need to verify the rpms at all. The reason is that the metadata contains the contant hashes for all the rpms we install, and we verify that this matches. Should we rather consider disabling the verification unconditionally?

Yeah, you're right. However, I think the repo metadata is not signed in practice and cannot be trusted on that level.

**Comment by atodorov** [comment]
FTR: This seems to be the reason for #566 (at least for me on 8.3 nightly) and also negatively affects any sort of internal testing where we've got unsigned packages.

**Comment by teg** [comment]
> How would osbuild-composer choose for which rpms to enable verification? 

Per repo, yes. But would need to somehow pass this information down to osbuild per-rpm, as osbuild currently does not have the concept of a repo (could introduce that, of course).

> Yeah, you're right. However, I think the repo metadata is not signed in practice and cannot be trusted on that level.

If the metadata is not trusted, then a roll-back attack would be fairly straight-forward. I know that fedora does not sign their metadata, and I seem to remember reading that this is ok due to the metalink being served over `https`. This is an odd argument in my view, but we could consider whether it is our job to "improve" on their security model?

**Comment by major** [comment]
How would this work in the situation where a customer adds a few RPMs from their internal repository? That repository might not be signed, but the customer may have some other trust setup that is sufficient for them. 🤷‍♂️

**Comment by larskarlitski** [comment]
> Per repo, yes. But would need to somehow pass this information down to osbuild per-rpm, as osbuild currently does not have the concept of a repo (could introduce that, of course).

Just as a follow up for everyone else: We discussed with @gicmo how osbuild could gain support for this.

> How would this work in the situation where a customer adds a few RPMs from their internal repository? That repository might not be signed, but the customer may have some other trust setup that is sufficient for them. man_shrugging

Yeah, another good point that we need this per repository. Thanks!

**Comment by gicmo** [comment]
In osbuild/osbuild#405 the plain `<sha1>: <url>` is extended to support `<sha1>: {url: <>, secrets: <>}`. This could be extended even further to include a `gpgkey` (or `gpgkey-id` with a global list of gpg keys). 
I am also still a bit unsure if we never want to do gpg verification, but I tend to think that having it at least optional with relying solely on the checksum of the package should be possible. Additionally, when the `ostree` source was added it was agreed that the verification should happen in the source and not the pipeline.

**Comment by teg** [comment]
In https://github.com/osbuild/osbuild/pull/409 I proposed dropping signature verification entirely. Which would solve the issue at hand, if merged.

**Comment by teg** [comment]
I'm now working on this again.

**Comment by teg** [comment]
As of https://github.com/osbuild/osbuild/pull/433 we again support building images with unsigned RPMs.
