### ISSUE TITLE
Implement missing /source commands and tests

### ISSUE THREAD

**Issue by teg** [osbuild/osbuild-composer#62]
This API is used to list and add custom sources. It is not fully implemented and tested yet.

Get as close as possible to Lorax’ implementation. At the least, managing custom source in the UI and all `composer-cli sources` commands must work. Start by implementing the tests for lorax, so that we know what to aim for in the osbuild implementation.

[API documentation](https://weldr.io/lorax/pylorax.api.html#module-pylorax.api.v0)

**Comment by jkozol** [comment]
The missing routes are:
```
POST /api/v0/projects/source/new
DELETE /api/v0/projects/source/delete/<source-name>
```

**Comment by larskarlitski** [comment]
This needs two things:
1. As @jkozol mentioned, sources have to be stored in the store now. Only store the user-added ones there, though (not the "base" one).
2. The ability to give multiple repositories to `dnf-json`. This is implemented in https://github.com/osbuild/osbuild-composer/pull/74, but most places in osbuild-composer still only pass one repository around.

**Comment by jkozol** [comment]
Per #77 I added functionality for sources but don't currently use the sources to fetch our package list. I should add the packages we fetch to the store instead of generating them on each call for the package list correct? Should this list be only for the user defined sources or include the base repo's sources?

**Comment by jkozol** [comment]
This has been completed with #103
