### ISSUE TITLE
Schutzbot CI cannot be viewed publicly

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/osbuild-composer#868]
Currently, Schutzbot lives behind the fence of Red Hat's internal network. This, unfortunately, means that contributors from the community cannot see test results of their PRs. This happened in https://github.com/osbuild/osbuild/pull/471.

It would be very nice if we can do something about it.

**Comment by teg** [comment]
This would be very nice indeed. I'm not sure what options we have there @major?

**Comment by major** [comment]
There are two main things in the way of getting Jenkins outside the firewall:

1. RHEL 8.3 content is only available inside the firewall.
2. PSI OpenStack API endpoints are only available inside the firewall

RHEL 8.3 beta content should be on the public CDN at some point, so that will make things better. We can do everything we're doing in AWS (or other clouds), so there's no reason why we can't put everything there (except for budget challenges).

**Comment by teg** [comment]
@major, would there be some way to mirror the results in some way, even if the infrastructure is still running on PSI?

**Comment by major** [comment]
We could publish the results somewhere and put a link in the PR via automation.

**Comment by atodorov** [comment]
> This would be very nice indeed. I'm not sure what options we have there @major?

copy the logs to S3 and inject the URL into the GitHub API calls which set the statuses on the PR. The second one would probably be harder b/c Jenkins plugins :-).

**Comment by msehnout** [comment]
This has been solved by the migration to Gitlab CI.
