### ISSUE TITLE
Fedora aarch64 tests fail due to enabled "updates" repository

### ISSUE THREAD

**Issue by msehnout** [osbuild/osbuild-composer#883]
The 4b0409df5b8128dbcf3c83f67893720840342e62 commit introduced updates repositories to Fedora aarch64 test cases. With this repository enabled, the test cases will get outdated very often (my guess would be every day).

My ideas for solution are:
 * update our test cases all the time
 * drop the repository, and workaround the issue mentioned in the commit message in a different way
 * create our own repository clone

but I'm sure there are different options.

**Comment by teg** [comment]
Thanks for opening this.

I think we should have our own repository clone(s) that most tests are run against. The only exceptions should be tests that specifically test the upstream repos and that things like the URL and certificate handling is correct.

Keeping a clone solves two problems:
 - stability: we control how flaky or not the mirrors are
 - content: by fixing the content and only replacing it when we choose to we are no longer at the mercy of the various distros and it allows us to tests against updates as well as rawhide without sacrificing the stability of our CI.

The workflow I propose:
 - Introduce some tool that clones a set of repos and puts them in S3 (or something like that). Make sure this new repo is content addressable so that we can have several at the same time and we don't need to coordinate with the consumers when we update (we add rather than replace, and just garbage collect when nobody uses it any more).
 - Update/regenerate tests to point to a new version of the repos independently, rely on the CI to verify that this works so if some distro introduces broken packages, we simply can't update our test cases.

@dvdhrm is working on something similar to this for manifestdb, but that usecase is more narrow, I suggest this as a general purpose solution for all our other testing so we can always be in control of what we test against.


I think we could and should use the same pinned content for generating our test images (using composer ;) ). For the same reason: we don't want things moving under us. @larskarlitski  had ideas in this direction, thoughts?

@major any thoughts on all this?

**Comment by ondrejbudai** [comment]
No longer relevant.
