### ISSUE TITLE
Add option for image tests to fail if no cloud credentials are found

### ISSUE THREAD

**Issue by atodorov** [osbuild/osbuild-composer#888]
In CI we should already have appropriate credentials for AWS, Azure and OpenStack but based on this comment https://github.com/osbuild/osbuild-composer/pull/880#issuecomment-662911028 I see that the image tests for AWS and OpenStack still fall back to qemu. 

I propose a command line option which will cause the tests to fail instead of falling back to qemu. That would be enabled in CI and will help us ensure testing is done in the cloud while also revealing any changes around authentication and credentials.

@ondrejbudai any comments ?

**Comment by ondrejbudai** [comment]
## The current state
### AWS
Is tested by [/test/image-tests/aws.sh](https://github.com/osbuild/osbuild-composer/blob/master/test/image-tests/aws.sh), this method uses `composer-cli` and `osbuild-composer` to do the upload. It isn't 100% predictable though because it builds the image with the ever-changing `updates` repository.

### Azure
Is tested by image tests. It doesn't use *the customer way* as `composer-cli` and `osbuild-composer` is not used. It's reliable though because the manifests are fixed and don't use `updates`.

As you can see, both cloud providers are covered in some way but I agree that having two different ways of testing the image is confusing.

## The possible future
We discussed this with @teg, I hope I remember the details well.

### Testing the cloud integration
We would like to move testing of the actual images out of `osbuild-composer` as much as possible. We can just test that the manifest isn't changing and rely on `manifestdb` to test that `osbuild` actually builds the proper image.

However, we need to test the integration with cloud APIs in `osbuild-composer`, so some image builds must be done here. To properly test the integration of all parts, this should use the current AWS approach - use `composer-cli` and `osbuild-composer` to build and upload the image. Then, these tests should use `awscli` or `azurecli` to create a vm and test if it can be booted.

This is very similar to how customers are using our software.

### Testing the images
`manifestdb` should be able to build images from well-defined manifests and test if they're booting. This, of course, means that we have to test them inside their target environment. Therefore, for `ami` image type we need to test if they boot inside `EC2`.

The workflow is that `manifestdb` builds the image and then uploads it somehow to the cloud (`composer` cannot be used as it cannot take a manifest as an input, some code can be shared though) and boots it there.

This should be very reliable as the manifest is fixed and the image is not changing all the time unpredictably.

**Comment by teg** [comment]
I agree with @ondrejbudai, this is the plan. However, until we have manifestdb up and running, let's not block on that. I also think having a commandline switch which would fail on missing credentials makes sense for CI. Maybe flip it around though, require them by default but have a switch that uses the fallback for local testing.
