### ISSUE TITLE
RHEL 8 image test cases still use download.devel.redhat.com

### ISSUE THREAD

**Issue by major** [osbuild/osbuild-composer#902]
We are unable to run images tests in AWS since the test cases all still point to download.devel.redhat.com.

**Comment by atodorov** [comment]
Can you edit the files, e.g. with sed, in the script which knows that it runs in AWS ?

**Comment by major** [comment]
The URLs are pretty different in the CDN. We could regenerate the test cases.

**Comment by teg** [comment]
I don't think we can change this with our current setup. I'm unsure if the beta repo on the CDN is static or receiving updates. Either case is problematic:
 - Each image test hardcodes the expected RPMs in the generated image, so if the repo is not static the tests will start failing as soon as an RPM is updated.
 - If the repo is static and unchanged since the beta was released, then we will be unable to update our test cases with content from newer nightlies, which we need in PR #893.

**Comment by major** [comment]
@teg I can confirm that the beta repo in the CDN *is* receiving updates.

**Comment by teg** [comment]
> @teg I can confirm that the beta repo in the CDN *is* receiving updates.

Thanks!

**Comment by atodorov** [comment]
> We are unable to run images tests in AWS since the test cases all still point to download.devel.redhat.com.

I believe this has been fixed long ago so closing this issue.
